import React, { useRef, useState, useCallback, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Character } from "@/characters";
import StorybookEmpty from "@/components/StorybookEmpty";
import { StorySceneGrid } from "@/components/StorySceneGrid";
import { AudioVisualizer } from "@/components/AudioVisualizer";
import { useLiveAPI, CharacterState, BadgeAward } from "@/hooks/useLiveAPI";
import { useStoryImages, StoryScene } from "@/hooks/useStoryImages";
import FloatingElements from "@/components/FloatingElements";
import BadgePopup from "@/components/BadgePopup";
import StoryRecapModal from "@/components/StoryRecapModal";

const THEMES_EMOJI: Record<string, string> = {
  Animals: "🦁", Space: "🚀", Kingdoms: "🏰", Ocean: "🌊", Food: "🍕",
  Jungle: "🌳", Magic: "🦄", Robots: "🤖", Spooky: "🎃", Adventure: "🏔️",
  Circus: "🎪", Dinosaurs: "🦕",
  Sharing: "🤝", Courage: "💪", Gratitude: "🙏", Creativity: "🎨", Kindness: "🌍",
};

// ── localStorage gallery ──────────────────────────────────────────────────────

export interface StoryGalleryEntry {
  id: string;
  characterId: string;
  characterName: string;
  characterImage: string;
  title: string;         // first 7 words of story transcript
  recapTitle?: string;   // proper storybook title generated by recap AI
  narrations?: string[]; // per-image captions generated by recap AI
  images: { imageData: string; mimeType: string }[];
  badges?: { emoji: string; name: string; reason: string }[];
  timestamp: number;
}

// Resize a base64 image before localStorage to stay within quota.
// 800px wide at JPEG 0.8 ≈ 100–200 KB — sharp enough to fill the storybook view (max-w-2xl = 672px).
function resizeImageForStorage(
  imageData: string,
  mimeType: string,
  maxWidth = 800,
): Promise<{ imageData: string; mimeType: string }> {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const scale = Math.min(1, maxWidth / img.width);
      const canvas = document.createElement("canvas");
      canvas.width = Math.round(img.width * scale);
      canvas.height = Math.round(img.height * scale);
      canvas.getContext("2d")?.drawImage(img, 0, 0, canvas.width, canvas.height);
      const resized = canvas.toDataURL("image/jpeg", 0.8).split(",")[1];
      resolve({ imageData: resized, mimeType: "image/jpeg" });
    };
    img.onerror = () => resolve({ imageData, mimeType }); // fall back to original on error
    img.src = `data:${mimeType};base64,${imageData}`;
  });
}

async function saveToGallery(
  sessionId: string,
  character: Character,
  scenes: StoryScene[],
  storyFirstLine: string,
  badges: { emoji: string; name: string; reason: string }[] = [],
) {
  // Resize each image to a thumbnail to stay within localStorage quota
  const rawImages = scenes
    .filter((s) => s.status === "loaded" && s.imageData)
    .map((s) => ({ imageData: s.imageData!, mimeType: s.mimeType! }));

  const images = await Promise.all(
    rawImages.map((img) => resizeImageForStorage(img.imageData, img.mimeType))
  );

  const title = storyFirstLine
    ? storyFirstLine.split(" ").slice(0, 7).join(" ") + "…"
    : `A story with ${character.name}`;

  try {
    const existing: StoryGalleryEntry[] = JSON.parse(
      localStorage.getItem("taleweaver_gallery") ?? "[]"
    );
    const prev = existing.find((e) => e.id === sessionId);
    const entry: StoryGalleryEntry = {
      id: sessionId,
      characterId: character.id,
      characterName: character.name,
      characterImage: character.image,
      title,
      recapTitle: prev?.recapTitle,
      // Prefer the latest images, but fall back to previously saved ones so
      // a second call (e.g. when opening the recap) never downgrades the entry.
      images: images.length > 0 ? images : (prev?.images ?? []),
      badges,
      timestamp: prev?.timestamp ?? Date.now(),
    };
    const updated = [entry, ...existing.filter((e) => e.id !== sessionId)].slice(0, 20);
    localStorage.setItem("taleweaver_gallery", JSON.stringify(updated));
    console.log(`[gallery] Saved session ${sessionId} — ${images.length} thumbnails, ${updated.length} total stories`);
  } catch (e) {
    console.warn("[gallery] localStorage save failed:", e);
  }
}

function updateGalleryEntry(sessionId: string, patch: Partial<StoryGalleryEntry>) {
  try {
    const existing: StoryGalleryEntry[] = JSON.parse(
      localStorage.getItem("taleweaver_gallery") ?? "[]"
    );
    const updated = existing.map((e) =>
      e.id === sessionId ? { ...e, ...patch } : e
    );
    localStorage.setItem("taleweaver_gallery", JSON.stringify(updated));
  } catch {
    // localStorage unavailable — ignore
  }
}

// ── Our Story end card ────────────────────────────────────────────────────────

function OurStoryCard({
  character,
  scenes,
}: {
  character: Character;
  scenes: StoryScene[];
}) {
  const lastImage = scenes.filter((s) => s.status === "loaded" && s.imageData).at(-1);

  return (
    <div className="relative flex-1 w-full h-full flex flex-col items-center justify-center overflow-hidden">
      {/* Last scene image as dimmed background */}
      {lastImage && (
        <img
          src={`data:${lastImage.mimeType};base64,${lastImage.imageData}`}
          alt=""
          className="absolute inset-0 w-full h-full object-cover opacity-30"
        />
      )}

      {/* Overlay gradient */}
      <div className="absolute inset-0 bg-gradient-to-b from-black/10 via-black/30 to-black/60" />

      {/* Content */}
      <motion.div
        initial={{ opacity: 0, scale: 0.92, y: 16 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        transition={{ duration: 0.5, ease: "easeOut" }}
        className="relative z-10 flex flex-col items-center gap-5 text-center px-8"
      >
        <div>
          <p className="font-display text-4xl font-bold text-white drop-shadow-lg">The End</p>
          <p className="font-body text-base text-white/80 mt-1">
            A story with {character.name}
          </p>
        </div>
      </motion.div>
    </div>
  );
}

// ── Component ─────────────────────────────────────────────────────────────────

const API_BASE = (import.meta.env.VITE_API_URL as string | undefined) ?? "";

interface Props {
  character: Character;
  theme?: string;
  propImage?: string;
  propDescription?: string;
  propImageMimeType?: string;
  onBack: () => void;
  onHome: () => void;
}

const AVATAR_STATE_CLASS: Record<CharacterState, string> = {
  idle:      "state-idle",
  thinking:  "state-thinking",
  speaking:  "state-speaking",
  listening: "state-listening",
};

const BORDER_CLASS: Record<CharacterState, string> = {
  idle:      "border-primary/40",
  thinking:  "border-violet-400/60",
  speaking:  "border-primary",
  listening: "border-cyan-400/70",
};

const PORTRAIT_ANIMATE: Record<CharacterState, object> = {
  idle:      { scale: [1, 1.018, 1] },
  thinking:  { rotate: [0, 3, -3, 3, -3, 0] },
  speaking:  { scale: [1, 1.06, 1] },
  listening: { y: [0, -5, 0] },
};

const PORTRAIT_TRANSITION: Record<CharacterState, object> = {
  idle:      { duration: 4,    repeat: Infinity, ease: "easeInOut" },
  thinking:  { duration: 2,    repeat: Infinity, ease: "easeInOut" },
  speaking:  { duration: 0.45, repeat: Infinity, ease: "easeInOut" },
  listening: { duration: 2.5,  repeat: Infinity, ease: "easeInOut" },
};

const STATUS_TEXT: Record<string, string> = {
  idle: "Ready to tell a story!",
  connecting: "Waking up the storyteller...",
  ready: "Almost ready — take a deep breath!",
  active_idle: "...",
  active_thinking: "Hmm, thinking of something wonderful...",
  active_speaking: "Telling the story...",
  active_listening: "I'm listening!",
  error: "Oops! Something went wrong. Try again!",
  ended: "The end! That was a great story!",
};

const StoryScreen = ({ character, theme, propImage, propDescription, propImageMimeType, onBack, onHome }: Props) => {
  const sessionIdRef = useRef<string>(crypto.randomUUID());
  const intervalSeconds = 8;

  // Story recap modal
  const [showRecap, setShowRecap] = useState(false);

  // Badge popup state (queue: show one at a time) + persistent list for saving
  const [activeBadge, setActiveBadge] = useState<BadgeAward | null>(null);
  const badgeQueueRef = useRef<BadgeAward[]>([]);
  const awardedBadgesRef = useRef<BadgeAward[]>([]);

  // Capture first story line for gallery title
  const storyFirstLineRef = useRef("");

  const { scenes, triggerImageGeneration, forceImageGeneration, stop: stopImages, seedPropImage } = useStoryImages(
    character.imageStyle,
    sessionIdRef.current,
    intervalSeconds
  );

  // Keep a stable ref to scenes for saving on end (state snapshot)
  const scenesRef = useRef<StoryScene[]>(scenes);
  scenesRef.current = scenes;

  const handleBadgeAwarded = useCallback((badge: BadgeAward) => {
    awardedBadgesRef.current = [...awardedBadgesRef.current, badge];
    badgeQueueRef.current.push(badge);
    setActiveBadge((prev) => prev ?? badgeQueueRef.current.shift() ?? null);
  }, []);

  const handleBadgeDismiss = useCallback(() => {
    const next = badgeQueueRef.current.shift() ?? null;
    setActiveBadge(next);
  }, []);

  const {
    connect, disconnect, togglePause, isPaused, sessionState, characterState, isCapturing,
    captureCtxRef, captureSourceRef, playbackCtxRef, playbackGainRef,
  } = useLiveAPI({
    character,
    theme,
    propImage,
    propDescription,
    onImageTrigger: triggerImageGeneration,
    onGenerateIllustration: forceImageGeneration,
    onTranscription: (msg) => {
      if (msg.type === "character" && !storyFirstLineRef.current) {
        storyFirstLineRef.current = msg.text;
      }
    },
    onBadgeAwarded: handleBadgeAwarded,
  });

  // Seed the prop illustration into the canvas as soon as the session goes active.
  // This ensures camera/sketch images appear immediately and prime visual continuity.
  useEffect(() => {
    if (sessionState === "active" && propImage && propImageMimeType) {
      seedPropImage(propImage, propImageMimeType, propDescription ?? "");
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionState]);

  // Auto-save to gallery whenever the session ends — regardless of whether
  // the user clicked "End Story" or the WebSocket closed unexpectedly.
  const prevSessionStateRef = useRef(sessionState);
  useEffect(() => {
    const prev = prevSessionStateRef.current;
    prevSessionStateRef.current = sessionState;
    if (
      (sessionState === "ended" || sessionState === "error") &&
      (prev === "active" || prev === "ready" || prev === "connecting")
    ) {
      void saveToGallery(sessionIdRef.current, character, scenesRef.current, storyFirstLineRef.current, awardedBadgesRef.current);
    }
  }, [sessionState, character]);

  const handleBegin = useCallback(() => {
    connect();
  }, [connect]);

  const endAndSave = useCallback(() => {
    void saveToGallery(sessionIdRef.current, character, scenesRef.current, storyFirstLineRef.current, awardedBadgesRef.current);
    stopImages();
    disconnect();
  }, [character, disconnect, stopImages]);

  const handleBack = () => {
    void saveToGallery(sessionIdRef.current, character, scenesRef.current, storyFirstLineRef.current, awardedBadgesRef.current);
    stopImages();
    disconnect();
    onBack();
  };

  const handleHome = () => {
    void saveToGallery(sessionIdRef.current, character, scenesRef.current, storyFirstLineRef.current, awardedBadgesRef.current);
    stopImages();
    disconnect();
    onHome();
  };

  // Called when the recap is opened — re-saves with the latest scenes (in case
  // images finished loading after endAndSave was called) and current badges.
  const handleShowRecap = () => {
    void saveToGallery(sessionIdRef.current, character, scenesRef.current, storyFirstLineRef.current, awardedBadgesRef.current);
    setShowRecap(true);
  };

  const avatarStateClass = AVATAR_STATE_CLASS[characterState];
  const isConnecting = sessionState === "connecting" || sessionState === "ready";
  const isActive = sessionState === "active";
  const statusKey = isActive ? `active_${characterState}` : sessionState;
  const statusText = STATUS_TEXT[statusKey] ?? "";

  return (
    <>
    {/* Badge popup and recap modal are outside the overflow-hidden container so that
        position:fixed works correctly on iOS/iPad (overflow:hidden clips fixed children) */}
    <AnimatePresence>
      {activeBadge && (
        <BadgePopup badge={activeBadge} onDismiss={handleBadgeDismiss} />
      )}
    </AnimatePresence>


    <div className="relative min-h-screen bg-sky-gradient overflow-hidden">
      <FloatingElements />

      <div className="relative z-10 h-screen flex flex-col">
        {/* Header */}
        <motion.header
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center justify-between px-4 sm:px-8 py-4 border-b border-border/30"
        >
          <div className="flex items-center gap-4">
            <button
              onClick={handleBack}
              className="text-muted-foreground hover:text-foreground font-body transition-colors"
            >
              ← Back
            </button>
            <button
              onClick={handleHome}
              className="text-muted-foreground hover:text-foreground font-body transition-colors"
            >
              Home
            </button>
          </div>
          <h1 className="font-display text-lg sm:text-xl font-bold text-primary">TaleWeaver</h1>
          <div className="flex items-center justify-end gap-3 flex-shrink-0">
            {theme && theme !== "camera_prop" && theme !== "sketch" && (
              <span className="whitespace-nowrap px-3 py-1 rounded-full bg-primary/20 border border-primary/30 font-body text-xs text-primary">
                {THEMES_EMOJI[theme] ?? "💭"} {theme}
              </span>
            )}
            {theme === "camera_prop" && (
              <span className="whitespace-nowrap px-3 py-1 rounded-full bg-primary/20 border border-primary/30 font-body text-xs text-primary">
                📸 Prop story
              </span>
            )}
            {theme === "sketch" && (
              <span className="whitespace-nowrap px-3 py-1 rounded-full bg-primary/20 border border-primary/30 font-body text-xs text-primary">
                ✏️ Sketch story
              </span>
            )}
          </div>
        </motion.header>

        {/* Main content */}
        <div className="flex-1 flex flex-col md:flex-row gap-4 p-4 sm:p-6 overflow-hidden">
          {/* Left — character panel */}
          <motion.div
            initial={{ opacity: 0, x: -40 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
            className="flex flex-col items-center justify-start md:w-1/5 gap-5 pt-4"
          >
            {/* Avatar */}
            <div className="relative flex items-center justify-center mt-4">
              {characterState === "speaking" && [0, 0.4, 0.8].map((delay, i) => (
                <motion.div
                  key={i}
                  className="absolute inset-0 rounded-full border-2 border-primary/50"
                  animate={{ scale: [1, 1.75], opacity: [0.6, 0] }}
                  transition={{ duration: 1.2, repeat: Infinity, delay, ease: "easeOut" }}
                />
              ))}
              {characterState === "thinking" && (
                <motion.div
                  className="absolute -top-2 -right-2 text-xl pointer-events-none select-none"
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: [0.5, 1, 0.5], y: [0, -5, 0] }}
                  transition={{ duration: 2, repeat: Infinity }}
                >
                  💭
                </motion.div>
              )}
              <motion.div
                key={characterState}
                className={`w-[8.25rem] h-[8.25rem] rounded-full overflow-hidden border-4 shadow-xl transition-colors duration-500 ${BORDER_CLASS[characterState]} ${avatarStateClass}`}
                initial={{ scale: 1, rotate: 0, y: 0 }}
                animate={PORTRAIT_ANIMATE[characterState]}
                transition={PORTRAIT_TRANSITION[characterState]}
              >
                <img src={character.image} alt={character.name} className="w-full h-full object-cover" />
              </motion.div>
            </div>

            {/* Name + language */}
            <div className="text-center">
              <h2 className="font-display text-2xl sm:text-3xl font-bold text-foreground">{character.name}</h2>
              <p className="text-sm text-muted-foreground font-body">{character.language} Storyteller</p>
            </div>

            {/* Status text */}
            <p className="font-body text-base text-foreground/70 text-center">{statusText}</p>

            {/* Active hint */}
            {isActive && (
              <p className="font-body text-xs text-foreground/40 text-center leading-relaxed px-2">
                Interrupt {character.name} anytime — just speak 🎙
              </p>
            )}

            {/* Speaking indicator bars */}
            <div className={`flex gap-1 items-end h-6 transition-opacity duration-300 ${characterState === "speaking" && isActive ? "opacity-100" : "opacity-0"}`}>
              {[0, 1, 2, 3, 4].map((i) => (
                <motion.div
                  key={i}
                  className="w-1.5 bg-primary rounded-full"
                  style={{ height: "20px", transformOrigin: "bottom" }}
                  animate={{ scaleY: [0.4, 1, 0.4] }}
                  transition={{ duration: 0.5, repeat: Infinity, delay: i * 0.1 }}
                />
              ))}
            </div>

            {/* Audio visualizers */}
            <div className={`flex flex-col gap-2 w-full px-2 transition-opacity duration-300 ${isActive ? "opacity-100" : "opacity-0"}`}>
              <div style={{ height: "40px" }}>
                <AudioVisualizer active={isActive} ctxRef={playbackCtxRef} nodeRef={playbackGainRef as React.RefObject<AudioNode | null>} color="hsl(42 100% 62%)" />
              </div>
              <div style={{ height: "40px" }}>
                <AudioVisualizer active={isCapturing} ctxRef={captureCtxRef} nodeRef={captureSourceRef as React.RefObject<AudioNode | null>} color="hsl(170 70% 50%)" />
              </div>
            </div>

            {/* Buttons */}
            <div className="flex flex-col items-center gap-2" style={{ minHeight: "80px" }}>
              {sessionState === "ended" ? (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-col items-center gap-2">
                  <button onClick={handleShowRecap} className="px-6 py-2 rounded-full bg-primary text-primary-foreground font-body text-sm font-semibold hover:brightness-110 transition-all">
                    📖 See our story!
                  </button>
                  <button onClick={handleBack} className="font-body text-sm px-6 py-2 rounded-full border border-border/60 text-muted-foreground hover:text-foreground hover:border-border transition-colors">
                    ✨ Begin another story
                  </button>
                </motion.div>
              ) : !isActive ? (
                <motion.button
                  initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3, delay: 0.8 }}
                  whileHover={!isConnecting ? { scale: 1.05 } : {}} whileTap={!isConnecting ? { scale: 0.95 } : {}}
                  onClick={handleBegin} disabled={isConnecting}
                  className="px-6 py-2.5 rounded-full bg-primary text-primary-foreground font-display text-base font-bold magic-glow animate-glow-pulse hover:brightness-110 transition-all disabled:opacity-60 disabled:cursor-not-allowed flex items-center gap-2"
                >
                  {isConnecting ? (
                    <>
                      <svg className="animate-spin h-6 w-6" viewBox="0 0 24 24" fill="none">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                      </svg>
                      Waking up the storyteller...
                    </>
                  ) : "🪄 Begin the Story!"}
                </motion.button>
              ) : (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3 }} className="flex flex-col items-center gap-2">
                  <div className="flex gap-2">
                    <button
                      onClick={togglePause}
                      className={`font-body text-sm px-4 py-2 rounded-full border transition-colors ${isPaused ? "border-primary/60 text-primary bg-primary/10 hover:bg-primary/20" : "border-border/60 text-muted-foreground hover:text-foreground hover:border-border"}`}
                    >
                      {isPaused ? "▶ Resume" : "⏸ Pause"}
                    </button>
                    <button onClick={endAndSave} className="font-body text-sm px-4 py-2 rounded-full border border-border/60 text-muted-foreground hover:text-foreground hover:border-border transition-colors">
                      End Story
                    </button>
                  </div>
                </motion.div>
              )}
            </div>
          </motion.div>

          {/* Right — story canvas */}
          <motion.div
            initial={{ opacity: 0, x: 40 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.5 }}
            className="flex-1 md:w-4/5 flex flex-col gap-1.5"
          >
            <div className="flex-1 story-canvas rounded-2xl border-2 border-dashed border-cycle overflow-hidden flex flex-col relative">
              {showRecap ? (
                <StoryRecapModal
                  character={character}
                  scenes={scenesRef.current}
                  badges={awardedBadgesRef.current}
                  onClose={() => setShowRecap(false)}
                  onRecapGenerated={(t, n) => updateGalleryEntry(sessionIdRef.current, { recapTitle: t, narrations: n })}
                />
              ) : sessionState === "ended" ? (
                <OurStoryCard
                  character={character}
                  scenes={scenes}
                />
              ) : scenes.length === 0 ? (
                <div className="flex-1 flex flex-col items-center justify-center gap-4 p-8">
                  <StorybookEmpty characterName={character.name} isActive={isActive} />
                </div>
              ) : (
                <div className="flex-1 relative">
                  <StorySceneGrid scenes={scenes} />
                </div>
              )}
            </div>
          </motion.div>
        </div>
      </div>
    </div>
    </>
  );
};

export default StoryScreen;
