export interface Character {
  id: string;
  name: string;
  tagline: string;
  emoji: string;
  description: string;
  cardGradient: string;
  bgColor: string;
  accentColor: string;
  textColor: string;
  greeting: string;
  imageStyle: string;
  isStudy?: boolean;
}

export const CHARACTERS: Character[] = [
  {
    id: "grandma-rose",
    name: "Grandma Rose",
    tagline: "Cozy bedtime tales",
    emoji: "👵",
    description: "Warm, gentle, and full of love. She knows every fairy tale ever told.",
    cardGradient: "from-pink-200 to-rose-300",
    bgColor: "#FFD1DC",
    accentColor: "#FF69B4",
    textColor: "#9D174D",
    greeting: "Hello sweetheart! I've been waiting for you. Shall we tell a story?",
    imageStyle: "warm watercolor illustration, storybook style, soft pastel colors, cozy and gentle, children's picture book art, golden hour lighting, heartwarming, detailed backgrounds",
  },
  {
    id: "captain-leo",
    name: "Captain Leo",
    tagline: "Bold adventures",
    emoji: "🧑‍✈️",
    description: "Brave, exciting, and ready for any adventure. Ahoy, young explorer!",
    cardGradient: "from-blue-200 to-blue-400",
    bgColor: "#B3D4FF",
    accentColor: "#2563EB",
    textColor: "#1E3A8A",
    greeting: "Ahoy there, young explorer! Ready for an adventure on the high seas?",
    imageStyle: "bold comic book illustration style, vibrant saturated colors, adventure and nautical themes, dynamic action poses, bright sky and ocean, children's adventure book art",
  },
  {
    id: "fairy-sparkle",
    name: "Fairy Sparkle",
    tagline: "Magical tales",
    emoji: "🧚",
    description: "Whimsical, magical, full of wonder. Every story she tells sparkles.",
    cardGradient: "from-purple-200 to-violet-400",
    bgColor: "#E8B4FF",
    accentColor: "#A855F7",
    textColor: "#6B21A8",
    greeting: "Oh! A visitor! I have the most wonderful magical story just waiting to be told!",
    imageStyle: "sparkly magical fantasy illustration, pastel rainbow colors, glitter and stars, enchanted forest, fairy tale art style, soft glowing light, magical creatures, flowers and butterflies",
  },
  {
    id: "professor-whiz",
    name: "Professor Whiz",
    tagline: "Science adventures",
    emoji: "🧑‍🔬",
    description: "Curious, clever, and endearingly absent-minded. Science is his magic!",
    cardGradient: "from-green-200 to-emerald-400",
    bgColor: "#B3FFD4",
    accentColor: "#10B981",
    textColor: "#065F46",
    greeting: "Fascinating! A young mind arrives! I have a most extraordinary story!",
    imageStyle: "colorful cartoon science illustration, bright cheerful laboratory, inventor workshop style, children's STEM art, gadgets and gizmos, colorful experiments, friendly robots, clean bright backgrounds",
  },
  {
    id: "dragon-blaze",
    name: "Dragon Blaze",
    tagline: "Silly dragon fun",
    emoji: "🐲",
    description: "Big, enthusiastic, and VERY excited. Every story is the BEST story EVER!",
    cardGradient: "from-orange-200 to-red-300",
    bgColor: "#FFD4B3",
    accentColor: "#F97316",
    textColor: "#9A3412",
    greeting: "ROAAARRR! Oh wait, I mean... hello! Ready for the most EPIC story EVER?!",
    imageStyle: "bold vibrant cartoon style, fiery bright orange and red colors, funny expressive dragon characters, action-comedy illustration, big eyes and expressions, energetic and dynamic, children's cartoon style",
  },
  // ── Indian language storytellers ─────────────────────────────────────────
  {
    id: "paati",
    name: "Paati",
    tagline: "Tamil கதைகள்",
    emoji: "👩‍🦳",
    description: "அன்பான தமிழ் பாட்டி. Warm Tamil grandmother with a treasure chest of folk tales.",
    cardGradient: "from-amber-100 to-orange-200",
    bgColor: "#FFE0B2",
    accentColor: "#C2410C",
    textColor: "#7C2D12",
    greeting: "வாங்க கண்ணா! என்னிடம் மிகவும் அழகான கதை இருக்கு. கேட்கணுமா?",
    imageStyle: "warm watercolor illustration, traditional Tamil village setting, rich saffron and deep magenta colors, jasmine flowers, kolam patterns, children's picture book art, golden lamp light, heartwarming",
  },
  {
    id: "dadi",
    name: "Dadi",
    tagline: "Hindi कहानियाँ",
    emoji: "👵",
    description: "प्यारी हिंदी दादी। A warm Hindi grandmother who knows every Panchatantra tale.",
    cardGradient: "from-teal-100 to-cyan-200",
    bgColor: "#B2EBF2",
    accentColor: "#0E7490",
    textColor: "#164E63",
    greeting: "आओ बेटा! दादी के पास बहुत सारी कहानियाँ हैं। सुनोगे ना?",
    imageStyle: "warm watercolor illustration, traditional North Indian village setting, rich teal and gold colors, marigold flowers, rangoli patterns, children's picture book art, soft evening lamp light, heartwarming",
  },
  {
    id: "ammamma",
    name: "Ammamma",
    tagline: "Telugu కథలు",
    emoji: "👩‍🦳",
    description: "అన్నపూర్ణ తెలుగు అమ్మమ్మ. Warm Telugu grandmother with Panchatantra and Tenali Rama tales.",
    cardGradient: "from-red-100 to-orange-200",
    bgColor: "#FFE8CC",
    accentColor: "#C2410C",
    textColor: "#7C2D12",
    greeting: "రా కన్నా! అమ్మమ్మ దగ్గర చాలా మంచి కథ ఉంది. వినాలా?",
    imageStyle: "warm watercolor illustration, traditional Telugu village setting, lotus flowers, rangoli with geometric patterns, red and gold colors, children's picture book art, golden lamp light, heartwarming",
  },
  {
    id: "aaji",
    name: "Aaji",
    tagline: "Marathi गोष्टी",
    emoji: "👩‍🦳",
    description: "माझ्या आजी. Warm Marathi grandmother with folk tales of clever crows and brave children.",
    cardGradient: "from-yellow-100 to-green-200",
    bgColor: "#F0FFF0",
    accentColor: "#15803D",
    textColor: "#14532D",
    greeting: "ये बाळा! आजीकडे आज एक मस्त गोष्ट आहे. ऐकणार का?",
    imageStyle: "warm watercolor illustration, traditional Maharashtrian village setting, marigold and green colors, tulsi plant, clay lamps, children's picture book art, soft evening light, heartwarming",
  },
  {
    id: "dida",
    name: "Dida",
    tagline: "Bengali গল্প",
    emoji: "👩‍🦳",
    description: "আমার দিদা. Warm Bengali grandmother with Thakurmar Jhuli folk tales.",
    cardGradient: "from-blue-100 to-indigo-200",
    bgColor: "#EFF6FF",
    accentColor: "#1D4ED8",
    textColor: "#1E3A8A",
    greeting: "এসো সোনা! দিদার কাছে আজ একটা দারুণ গল্প আছে। শুনবে?",
    imageStyle: "warm watercolor illustration, traditional Bengali village setting, mustard fields, hilsa fish motifs, blue and gold colors, earthen lamps, children's picture book art, heartwarming",
  },
  // ── Study characters ──────────────────────────────────────────────────────
  {
    id: "count-cosmo",
    name: "Count Cosmo",
    tagline: "Maths adventures",
    emoji: "🚀",
    description: "A friendly astronaut who teaches counting, shapes, and patterns through space adventures!",
    cardGradient: "from-indigo-200 to-purple-300",
    bgColor: "#EDE9FE",
    accentColor: "#7C3AED",
    textColor: "#4C1D95",
    greeting: "3... 2... 1... Blast off! Welcome aboard, little mathematician!",
    imageStyle: "colorful cartoon space illustration, friendly astronaut, floating numbers and shapes, stars and planets, bright cheerful backgrounds, children's educational book art",
    isStudy: true,
  },
  {
    id: "dr-luna",
    name: "Dr. Luna",
    tagline: "Science & Nature",
    emoji: "🔬",
    description: "A warm scientist who sparks wonder about animals, plants, weather, and the universe!",
    cardGradient: "from-green-200 to-teal-300",
    bgColor: "#F0FFF4",
    accentColor: "#0D9488",
    textColor: "#134E4A",
    greeting: "Oh wonderful — a curious mind! Did you know caterpillars turn to soup before becoming butterflies?",
    imageStyle: "bright nature illustration, friendly scientist in a sunflower field, colorful animals, rainbows, cheerful lab, children's science book art",
    isStudy: true,
  },
  {
    id: "professor-pip",
    name: "Professor Pip",
    tagline: "Words & Reading",
    emoji: "🦉",
    description: "A wise bookworm owl who makes letters, words, and stories feel absolutely magical!",
    cardGradient: "from-yellow-200 to-amber-300",
    bgColor: "#FFFBEB",
    accentColor: "#D97706",
    textColor: "#78350F",
    greeting: "Hoo hoo! Every letter is a little spell waiting to be cast. Ready to read?",
    imageStyle: "cozy library illustration, friendly bookworm owl, colorful alphabet letters floating, storybook pages, warm golden light, children's reading book art",
    isStudy: true,
  },
  {
    id: "arty",
    name: "Arty",
    tagline: "Art & Colours",
    emoji: "🎨",
    description: "A splashy, creative artist who teaches colors, shapes, and the joy of making things!",
    cardGradient: "from-pink-200 to-purple-300",
    bgColor: "#FDF4FF",
    accentColor: "#9333EA",
    textColor: "#581C87",
    greeting: "Hello hello! Grab your crayons — we're about to make something BEAUTIFUL!",
    imageStyle: "vibrant watercolor splashes, paint palette, rainbow explosion, friendly paintbrush character, colorful abstract children's art",
    isStudy: true,
  },
];

export const getCharacter = (id: string) => CHARACTERS.find((c) => c.id === id);
